### ISSUE TITLE
请问如何打包

### ISSUE THREAD

**Issue by zzzttt1017** [liutaigang/vscode-webview-extension-example#2]
感谢大佬的付出！我想尝试下如何打包，请问该如何做呀

**Comment by zzzttt1017** [comment]
原来是要进extension下打包，找到了！谢谢！

**Comment by liutaigang** [comment]
我在根目录新增打包的脚本， 依次运行
`pnpm i`
`pnpm  build`
`pnpm  package`
就可以了
![image](https://github.com/liutaigang/vscode-webview-extension-example/assets/110760655/e8aea529-e1e3-454a-84d3-5498ae54e6bb)
