### ISSUE TITLE
pnpm dev 没有构建插件模块

### ISSUE THREAD

**Issue by Nick742037091** [liutaigang/vscode-webview-extension-example#3]
![image](https://github.com/liutaigang/vscode-webview-extension-example/assets/20139399/3f24d611-5013-4c13-a746-9ffe0a03b8a7)

pnpm dev 没有构建插件模块，得把`run-p dev:view-*`改成`run-p dev:*`

**Comment by liutaigang** [comment]
开发的时候，一般是使用 F5 开启调试，会自动执行 npm run dev:extension，所以就没有必要了
![image](https://github.com/liutaigang/vscode-webview-extension-example/assets/110760655/52b84f23-26b3-4a95-98b7-9e32eee9de0b)
