### ISSUE TITLE
请问下vscode-codicons加载失败怎么处理？

### ISSUE THREAD

**Issue by qadyuanzai** [liutaigang/vscode-webview-extension-example#4]
[vscode-codicons](https://github.com/microsoft/vscode-codicons)
[webview-codicons-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-codicons-sample)
安装完后使用
``` vue
</script>
import '@vscode/codicons/dist/codicon.css';
</script>
<template>
    <span class="codicon codicon-home"></span>
</template>
```
显示的效果为
![image](https://github.com/liutaigang/vscode-webview-extension-example/assets/42380987/3e17b697-2300-488a-8128-fb390b9f0941)
有一个网络请求是这样的
![image](https://github.com/liutaigang/vscode-webview-extension-example/assets/42380987/fd1e14e5-a7fa-409e-b888-611fcde68e30)
想问下怎么处理？

**Comment by qadyuanzai** [comment]
我现在是在extension中也添加了这个字体库，然后在文本解析方法 getWebviewHtml 里添加了这一段
```
const codiconsUri = webview.asWebviewUri(Uri.joinPath(this.context.extensionUri, 'node_modules', '@vscode/codicons', 'dist', 'codicon.css'));
htmlText = htmlText.replace("<head>", "<head> \
  <link rel=\"stylesheet\" href=\"" + codiconsUri + "\"> \
");
```
运行是可以运行了，但是太不优雅了😂

**Comment by liutaigang** [comment]
你这样写的目的是为了拼接 this.context.extensionUri， 但其实已经统一实现了：
![截屏2024-06-23 15 05 54](https://github.com/liutaigang/vscode-webview-extension-example/assets/110760655/05c7d10e-f3e9-4f35-ba72-4f5656767dbb)
所以你只需要在项目的 index.html 中新增 <link> 就可以了：
![image](https://github.com/liutaigang/vscode-webview-extension-example/assets/110760655/534e06eb-67e1-4bd5-9046-91a926a1469b)

**Comment by qadyuanzai** [comment]
感谢，现在我这边算是解决了，需要把资源从包里复制一份到public文件夹中就可以访问到了
![image](https://github.com/liutaigang/vscode-webview-extension-example/assets/42380987/b1b248d6-f687-4078-95c4-b3d3a872ae45)
![image](https://github.com/liutaigang/vscode-webview-extension-example/assets/42380987/539dc675-2788-4449-ba78-7d81da0c244d)
